import React from "react";
import Captive from '../assets/images/captive.png'
import Recycle from '../assets/images/recycle.png'
import Certified from '../assets/images/certified.png'

const RenewalStrength = () => {

  return (

    <>

      <section className="gsi-bg">
        <div className="gsi-overlay"></div>

        <div className="gsi-container">
          {/* Header */}
          <div className="gsi-header">
            <div className="gsi-header-left">
              <span className="gsi-tag">
                Shreyas Renewable Energies Integration
              </span>
              <h2 className="gsi-title">Green Steel Initiative</h2>
            </div>

            <div className="gsi-header-right">
              <p>
                “Produced with a significantly lower carbon footprint through our
                captive renewable energy integration.”
              </p>
            </div>
          </div>

          {/* Stats Cards */}
          <div className="gsi-cards">
            <div className="gsi-card">
              <div className="gsi-icon"><img src={Captive} className="gs-icon-img" /></div>
              <h3>100%</h3>
              <p>Captive Power Generation</p>
            </div>

            <div className="gsi-card">
              <div className="gsi-icon"><img src={Recycle} className="gs-icon-img" /></div>
              <h3>40%</h3>
              <p>Lower Carbon Emissions</p>
            </div>

            <div className="gsi-card">
              <div className="gsi-icon"><img src={Certified} className="gs-icon-img" /></div>
              <h3>Certified</h3>
              <p>Sustainable Manufacturing</p>
            </div>
          </div>

          {/* Footer Text */}
          <p className="gsi-footer-text">
            The Synergistic Advantage: Shreyas Iron & Steel utilizes the green
            power generated by Shreyas Renewable Energies, creating a vertically
            integrated sustainable steel production ecosystem.
          </p>
        </div>
      </section>

    </>

  )


}
export default RenewalStrength;